apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent

resources:
- rbac.yaml
- service.yaml
- deployment.yaml

configMapGenerator:
- name: copilot-gateway-scripts
  files:
  - ../src/auth_rotator.py
  - ../src/proxy_server.py
