apiVersion: v1
kind: Secret
metadata:
  name: copilot-oauth-credentials
  namespace: kagent
type: Opaque
stringData:
  client-id: "Ov23liNgHNsuDCsVBxaX"
  client-secret: "bcb6a8bf68b7e6e7f33d053ae85c2203a5244c3b"
